git commit
Learn-Adapt-Build/DiscoBall-App pull request #9
Opened 2024-10-23 22:48 UTC by Gosha04

2024-10-23 22:50 UTC, Gosha04 commented
Questions were changed

2024-10-23 22:57 UTC, spencerau commented
@Gosha04 can you sync with the dev-fall2024 upstream and then edit your questions.json file so that it has the hexcode colors for each answer?

https://github.com/Learn-Adapt-Build/DiscoBall-App/blob/dev-fall2024/web-app/public/questions.json

2024-10-24 00:08 UTC, Gosha04 commented
I don't have a clue what colors each answer should have, I wasn't really briefed on that. Is there a doc with all the hexcodes?

________________________________
From: Spencer Au ***@***.***>
Sent: Wednesday, October 23, 2024 3:57 PM
To: Learn-Adapt-Build/DiscoBall-App ***@***.***>
Cc: Vaysman, Joshua (Student) ***@***.***>; Mention ***@***.***>
Subject: Re: [Learn-Adapt-Build/DiscoBall-App] git commit (PR #9)

External Message


@Gosha04<https://github.com/Gosha04> can you sync with the dev-fall2024 upstream and then edit your questions.json file so that it has the hexcode colors for each answer?

https://github.com/Learn-Adapt-Build/DiscoBall-App/blob/dev-fall2024/web-app/public/questions.json

—
Reply to this email directly, view it on GitHub<https://github.com/Learn-Adapt-Build/DiscoBall-App/pull/9#issuecomment-2433687925>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BCH6IDWQUKSVIPH5SONXFJTZ5ASW7AVCNFSM6AAAAABQP2FB3CVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIMZTGY4DOOJSGU>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

NOTE: This email originated from outside Chapman’s network. Do not click links or open attachments unless you recognize the sender and know content is safe.

2024-10-24 00:09 UTC, spencerau commented
Yes the document linked at questions.json has the hexcodes

2024-10-24 03:21 UTC, Gosha04 commented
Added
________________________________
From: Spencer Au ***@***.***>
Sent: Wednesday, October 23, 2024 5:09 PM
To: Learn-Adapt-Build/DiscoBall-App ***@***.***>
Cc: Vaysman, Joshua (Student) ***@***.***>; Mention ***@***.***>
Subject: Re: [Learn-Adapt-Build/DiscoBall-App] git commit (PR #9)

External Message


Yes the document linked at questions.json has the hexcodes

—
Reply to this email directly, view it on GitHub<https://github.com/Learn-Adapt-Build/DiscoBall-App/pull/9#issuecomment-2433851922>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BCH6IDUFPI3ZCHJ3OFCCHCDZ5A3FJAVCNFSM6AAAAABQP2FB3CVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIMZTHA2TCOJSGI>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

NOTE: This email originated from outside Chapman’s network. Do not click links or open attachments unless you recognize the sender and know content is safe.

2024-10-24 04:32 UTC, spencerau requested changes

2024-10-24 04:32 UTC, spencerau commented on web-app/public/questions.json
Why does this only have 14 questions?

2024-10-24 04:37 UTC, spencerau commented on web-app/public/questions.json
Why does this only have 14 questions

2024-10-24 04:38 UTC, spencerau commented on web-app/public/questions_db.json
Can you delete this and/or update your fork to the upstream, so sync it with LAB:dev-fall2024

2024-10-24 04:38 UTC, spencerau requested changes
See comments

2024-10-24 04:41 UTC, Gosha04 commented on web-app/public/questions.json
Not sure. Maybe deleted some in while adding colors? I'll look it over

2024-10-24 04:41 UTC, closed without merging